server:
  port: 8090
  mode: debug

database:
  driver: mysql
  host: localhost
  port: 3306
  username: root
  password: 123456789
  dbname: robot
  charset: utf8mb4
  parse_time: true
  loc: Local

jwt:
  secret: your-secret-key
  expire: 24 # hours